import pandas as pd
import numpy as np


# =========================================================
# 1. MAKE RESULTS REPRODUCIBLE
# =========================================================

np.random.seed(42)


# =========================================================
# 2. LIST OF CROPS
# =========================================================

crops = [

    # -------- Vegetables --------
    "Tomato",
    "Onion",
    "Potato",
    "Carrot",
    "Cabbage",
    "Green Chilli",
    "Brinjal",
    "Cucumber",
    "Green Peas",
    "Sweet Corn",
    "Broccoli",
    "Spinach",
    "Capsicum",
    "Beans",
    "Pumpkin",

    # -------- Grains --------
    "Wheat",
    "Rice"
]


# =========================================================
# 3. MAHARASHTRA LOCATIONS
# =========================================================

locations = [

    "Pune",
    "Nashik",
    "Nagpur",
    "Mumbai",
    "Aurangabad",
    "Kolhapur",
    "Sangli",
    "Satara",
    "Ahmednagar",
    "Solapur"

]


# =========================================================
# 4. BASE DEMAND FOR EACH CROP
# =========================================================
# This is demo/synthetic data for your prototype.
# Higher number = higher average demand.
# =========================================================

crop_demand = {

    # -------- Vegetables --------

    "Tomato": 500,

    "Onion": 650,

    "Potato": 600,

    "Carrot": 350,

    "Cabbage": 300,

    "Green Chilli": 250,

    "Brinjal": 320,

    "Cucumber": 280,

    "Green Peas": 220,

    "Sweet Corn": 270,

    "Broccoli": 180,

    "Spinach": 200,

    "Capsicum": 260,

    "Beans": 240,

    "Pumpkin": 300,

    # -------- Grains --------

    "Wheat": 750,

    "Rice": 850

}


# =========================================================
# 5. LOCATION DEMAND FACTOR
# =========================================================
# This represents the approximate additional demand
# generated by each location in our prototype.
# =========================================================

location_factor = {

    "Pune": 100,

    "Nashik": 80,

    "Nagpur": 70,

    "Mumbai": 180,

    "Aurangabad": 50,

    "Kolhapur": 40,

    "Sangli": 30,

    "Satara": 35,

    "Ahmednagar": 45,

    "Solapur": 60

}


# =========================================================
# 6. CREATE 180 DAYS OF HISTORICAL DATA
# =========================================================

dates = pd.date_range(

    start="2026-01-01",

    periods=180,

    freq="D"

)


# Empty list to store all records

data = []


# =========================================================
# 7. GENERATE DEMAND DATA
# =========================================================

for crop in crops:

    for location in locations:

        for i, date in enumerate(dates):


            # -------------------------------------------------
            # Base demand according to crop
            # -------------------------------------------------

            demand = crop_demand[crop]


            # -------------------------------------------------
            # Add location effect
            # -------------------------------------------------

            demand += location_factor[location]


            # -------------------------------------------------
            # Gradual demand growth over time
            # -------------------------------------------------

            demand += i * 0.8


            # -------------------------------------------------
            # Weekend effect
            # -------------------------------------------------
            # People may purchase more during weekends.
            # -------------------------------------------------

            if date.dayofweek >= 5:

                demand += 40


            # -------------------------------------------------
            # Seasonal demand variation
            # -------------------------------------------------

            seasonal_effect = 30 * np.sin(

                2 * np.pi * i / 30

            )

            demand += seasonal_effect


            # -------------------------------------------------
            # Random variation
            # -------------------------------------------------
            # Makes the dataset look more realistic.
            # -------------------------------------------------

            random_variation = np.random.randint(

                -30,

                31

            )

            demand += random_variation


            # -------------------------------------------------
            # Prevent negative demand
            # -------------------------------------------------

            demand = max(

                demand,

                50

            )


            # =================================================
            # GENERATE PRICE
            # =================================================

            price = (

                20 +

                np.random.uniform(

                    -3,

                    5

                )

            )


            # =================================================
            # STORE RECORD
            # =================================================

            data.append({

                "date": date,

                "crop": crop,

                "location": location,

                "demand_kg": round(

                    demand,

                    2

                ),

                "price": round(

                    price,

                    2

                )

            })


# =========================================================
# 8. CONVERT DATA INTO DATAFRAME
# =========================================================

df = pd.DataFrame(data)


# =========================================================
# 9. SAVE DATASET AS CSV
# =========================================================

df.to_csv(

    "demand_data.csv",

    index=False

)


# =========================================================
# 10. DISPLAY INFORMATION
# =========================================================

print()
print("==========================================")
print("       DATASET CREATED SUCCESSFULLY")
print("==========================================")

print()

print(
    "Total records:",
    len(df)
)

print(
    "Total crops:",
    len(crops)
)

print(
    "Total locations:",
    len(locations)
)

print(
    "Days of historical data:",
    len(dates)
)

print()

print("Crops included:")

for crop in crops:

    print(
        " -",
        crop
    )

print()

print("Maharashtra locations included:")

for location in locations:

    print(
        " -",
        location
    )

print()

print("First 10 records:")

print(
    df.head(10)
)

print()

print(
    "File saved as: demand_data.csv"
)

print("==========================================")